### ISSUE TITLE
abort when enter `set cmdheight=0`

### ISSUE THREAD

**Issue by tachibana51** [tachibana51/neovim#1]
### Neovim version (nvim -v)

0.6.0-dev+nightly-27-g8836d55d9

### Vim (not Nvim) behaves the same?

no

### Operating system/version

`Linux desktop 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Terminal name/version

alacritty and gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

`nvim --clean`
`:set cmdheight=0`

### Expected behavior

Exact behavior discussion is still underway, but crash / aborting is not expected.
rel https://github.com/neovim/neovim/pull/16251

### Actual behavior

```                                                                                                                                                                 
nvim: ../src/nvim/screen.c:5964: grid_puts_line_flush: Assertion `put_dirty_row != -1' failed.                                                                                            
                                                                                              fish: Job 1, './nvim --clean' terminated by signal SIGABRT (Abort)
```

**Comment by tachibana51** [comment]
Maybe this behavior occurs by some global flags for buffering. I'm fixing (and reading contributing guideline, this is my first work for this project).

**Comment by tachibana51** [comment]
I was able to understand about half of the causes of this problem. 
The direct cause of this bug is not modifying of global variables in PRs commits.  
When `display_showcmd` calls `msg_grid_validate` in `grid_puts_line_start`, `msg_grid_validate` will call `msg_grid_set_pos`. 
At this time, If `p_ch` is 0, `msg_grid.chars` is `:\x00\x00\x00...`, so `msg_grid_adj.row_offset = -row` will run.
As a result, `grid_puts_line_start` sets` put_dirty_row` to -1 with `put_dirty_row = row`, which also fails the assertion of` grid_puts_line_flush`.

I have rough solution such as  ` if (msg_grid.chars && strcmp(":", msg_grid.chars) != 0) {`(of course, the argument types in this code are incorrect), but I'm not sure if this is correct for the whole code.

**Comment by Shougo** [comment]
Hi, I have fixed `display_showcmd()` problem.
Please test the latest version.

**Comment by tachibana51** [comment]
I don't know if it's the correct fix because there aren't many tests, but I'm sure it will not abort.

**Comment by Shougo** [comment]
OK. Thanks
